package org.javarush.cipher.caesar.command;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class HackCaesarCommandTest {
    @Test
    void processContent_emptyContent() {
        HackCaesarCommand hackCommand = new HackCaesarCommand("");
        String result = hackCommand.processContent("");

        assertEquals("", result, "Expected decrypted content to be empty for empty input");
    }

    @Test
    void processContent_singleCharacterEncrypted() {
        HackCaesarCommand hackCommand = new HackCaesarCommand("");
        String result = hackCommand.processContent("kyvtrmrcipnzccrkkrtbwifdkyvefikynvjkrkeffe");

        assertEquals("thecavalrywillattackfromthenorthwestatnoon", result, "Expected decrypted content to be 'A' for single character encrypted 'A'");
    }

    @Test
    void getDestFilePath_validFilePath_returnsExpectedFilePath() {
        String testFilePath = "C:\\test\\file.txt";
        HackCaesarCommand hackCommand = new HackCaesarCommand(testFilePath);

        String expectedFilePath = "C:\\test\\file.txt[HACKED]";

        assertEquals(expectedFilePath, hackCommand.getDestFilePath(testFilePath),
                "Expected filepath does not match with the filepath generated by getDestFilePath method");
    }
}
